### ISSUE TITLE
TransactionChargeError: Your account charge call failed with message: Your account status is pending confirmation

### ISSUE THREAD

**Issue by eliemugenzi** [Flutterwave/rave-python#71]
I'm having an issue when I'm charging with mobile money, let me know if I can get support.

##### Currency
- RWF (Rwandan Francs)

##### Country

- Rwanda

#### Code sample

```
from rave_python.rave import GhMobile


rave=GhMobile(PUBLIC_KEY, SECRET_KEY, production=True, usingEnv=False)

class MomoPayments:

    def __init__(self, momoDetails):
        self.network=momoDetails['network']
        self.phone_number=momoDetails['phone_number']
        self.email=momoDetails['email']
        self.ip=momoDetails['IP']
        self.amount=momoDetails['amount']


    def pay(self):
        
        payload={
            'network': self.network,
            'phonenumber': self.phone_number,
            'IP': self.ip,
            'amount': self.amount,
            'email': self.email,
            'redirect_url': 'https://rave-webhook.herokuapp.com/receivepayment'
        }

        response=rave.charge(payload)
        print(response)


momoDetails={
    'network': 'RWF',
    'amount': '100',
    'phone_number': '250785844487',
    'IP': '343453453455',
    'email': 'eliemugenzi@gmail.com'
}

payment=MomoPayments(momoDetails)

payment.pay()
```

#### The error I'm getting

```
Traceback (most recent call last):
  File "payments/flutterwave/mobilemoney.py", line 41, in <module>
    payment.pay()
  File "payments/flutterwave/mobilemoney.py", line 27, in pay
    response=rave.charge(payload)
  File "/home/elie/Projects/XpressCash/backend-1/env/lib/python3.7/site-packages/rave_python/rave_ghmobile.py", line 33, in charge
    return super(GhMobile, self).charge(accountDetails, requiredParameters, endpoint)
  File "/home/elie/Projects/XpressCash/backend-1/env/lib/python3.7/site-packages/rave_python/rave_payment.py", line 209, in charge
    return self._handleChargeResponse(response, paymentDetails["txRef"])
  File "/home/elie/Projects/XpressCash/backend-1/env/lib/python3.7/site-packages/rave_python/rave_payment.py", line 69, in _handleChargeResponse
    res = self._preliminaryResponseChecks(response, TransactionChargeError, txRef=txRef)
  File "/home/elie/Projects/XpressCash/backend-1/env/lib/python3.7/site-packages/rave_python/rave_payment.py", line 61, in _preliminaryResponseChecks
    raise TypeOfErrorToRaise({"error": True, "txRef": txRef, "flwRef": flwRef, "errMsg": errMsg})
rave_python.rave_exceptions.TransactionChargeError: Your account charge call failed with message: Your account status is pending confirmation
```

**Comment by Corvus97** [comment]
Hello @eliemugenzi , Kindly confirm if your account has been verified. If it has, please send an email to hi@flutterwavego.com for the issue to be resolved.
